name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Verify environment variables
        run: |
          if [ -z "$REACT_APP_RECAPTCHA_SITE_KEY" ]; then echo "REACT_APP_RECAPTCHA_SITE_KEY is not set"; else echo "REACT_APP_RECAPTCHA_SITE_KEY is set"; fi
          if [ -z "$REACT_APP_RECAPTCHA_SITE_SECRET" ]; then echo "REACT_APP_RECAPTCHA_SITE_SECRET is not set"; else echo "REACT_APP_RECAPTCHA_SITE_SECRET is set"; fi
          if [ -z "$REACT_APP_EMAILJS_SERVICE_ID" ]; then echo "REACT_APP_EMAILJS_SERVICE_ID is not set"; else echo "REACT_APP_EMAILJS_SERVICE_ID is set"; fi
          if [ -z "$REACT_APP_EMAILJS_TEMPLATE_ID" ]; then echo "REACT_APP_EMAILJS_TEMPLATE_ID is not set"; else echo "REACT_APP_EMAILJS_TEMPLATE_ID is set"; fi
          if [ -z "$REACT_APP_EMAILJS_PUBLIC_KEY" ]; then echo "REACT_APP_EMAILJS_PUBLIC_KEY is not set"; else echo "REACT_APP_EMAILJS_PUBLIC_KEY is set"; fi
        env:
          REACT_APP_RECAPTCHA_SITE_KEY: ${{ secrets.REACT_APP_RECAPTCHA_SITE_KEY }}
          REACT_APP_RECAPTCHA_SITE_SECRET: ${{ secrets.REACT_APP_RECAPTCHA_SITE_SECRET }}
          REACT_APP_EMAILJS_SERVICE_ID: ${{ secrets.REACT_APP_EMAILJS_SERVICE_ID }}
          REACT_APP_EMAILJS_TEMPLATE_ID: ${{ secrets.REACT_APP_EMAILJS_TEMPLATE_ID }}
          REACT_APP_EMAILJS_PUBLIC_KEY: ${{ secrets.REACT_APP_EMAILJS_PUBLIC_KEY }}
      - name: Build project
        env:
          REACT_APP_RECAPTCHA_SITE_KEY: ${{ secrets.REACT_APP_RECAPTCHA_SITE_KEY }}
          REACT_APP_RECAPTCHA_SITE_SECRET: ${{ secrets.REACT_APP_RECAPTCHA_SITE_SECRET }}
          REACT_APP_EMAILJS_SERVICE_ID: ${{ secrets.REACT_APP_EMAILJS_SERVICE_ID }}
          REACT_APP_EMAILJS_TEMPLATE_ID: ${{ secrets.REACT_APP_EMAILJS_TEMPLATE_ID }}
          REACT_APP_EMAILJS_PUBLIC_KEY: ${{ secrets.REACT_APP_EMAILJS_PUBLIC_KEY }}
          GENERATE_SOURCEMAP: false
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
